### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Godsmack121Kcamsdog** [GoodieBag/CarouselPicker#1]
How to change picker items textColor?

**Comment by KoderKrishanu** [comment]
Hi @Godsmack121Kcamsdog 
Currently, we've not implemented the feature, will update in next 2-3 days.

**Comment by Godsmack121Kcamsdog** [comment]
Okey, that`s great. Please, could you also let the ability to determine
TextAlligment using CarouselPicker.TextItem. Or implement the solution via
Adapter+ViewHolder with using custom View model.

2017-07-06 17:19 GMT+03:00 Krishanu <notifications@github.com>:

**Comment by Astralgr** [comment]
@KoderKrishanu 
Hello, did you have the time to look into changing text color ?

**Comment by Godsmack121Kcamsdog** [comment]
Hello!
Unfortunately, no.
I decided to use simple RecyclerView in my application long time ago.
Sorry.

I will try it later, if it may be possible.

24 Сен 2017 г. 10:04 PM пользователь "Marios Bar" <notifications@github.com>
написал:

**Comment by Astralgr** [comment]
@Godsmack121Kcamsdog 
Thanks for the reply managed to do it myself, wasn't so hard at the end

**Comment by VladyIliev** [comment]
Could anyone share a solution to the problem?

**Comment by VladyIliev** [comment]
Solved:
Copy the _CarouselViewAdapter_ class, and in method _instantiateItem_ add tv.setTextColor(your color here).

**Comment by VladyIliev** [comment]
Solved:
Copy the _CarouselViewAdapter_ class, and in method _instantiateItem(ViewGroup container, int position)_ add _tv.setTextColor(your color here)_.

**Comment by Hello911** [comment]
@VladyIliev , Hi, I used dependecy and compile to use the library. I wanted to change text color, so I created CarouselPicker.java class and modify the instatiateItem() as you said, but afterward, it says "CarouselViewAdapter class is never used". And the text color didn't change.

**Comment by VladyIliev** [comment]
_Don't_ create a whole new _CarouselPicker_, you need just the contents of _CarouselViewAdapter_ (it extends PageAdapter). Then, using the carousel (the actual CarouselPicker), use _setAdapter()_ to link your new modified adapter.

**Comment by Hello911** [comment]
Do I need to create a new java file called CarouselViewAdapter? I cannot modify an external dependency. The file is read only.

**Comment by VladyIliev** [comment]
@Hello911 You can create a new class, but you either need to pick a new name of your own, or specify the full package/class path to avoid conflicts (similar to what your imports look like). In my case, I created a nested inner class, because a separate file wouldn't be necessary. For reference, here is the carousel I implemented: https://pastebin.com/J7maWNbe. You should pay attention only to the nested inner class, and the setAdapter() method called within my updateVisibleLocations() method.

**Comment by Vatican-Cameos** [comment]
Hello,
I apologise for the delayed response and delaying this fix. We were knees deep into work in the past year and we were not able to maintain this repository.   

This issue has been fixed.  
Please update your Gradle file and replace the old implementation with this :   
```implementation 'com.github.GoodieBag:CarouselPicker:v1.1'```

Now you will have access to :     
```adapter.setTextColor(colorInt)``` method which will change the text item's textColor.

Please let me know if it works as expected. Will leave the issue open for a day or two before closing this.

Best,
Pavan
