### ISSUE TITLE
Possible to save starting position?

### ISSUE THREAD

**Issue by Brian-Yeh** [GoodieBag/CarouselPicker#4]
Is there any way to set the starting position of the carousel? Say I have numbers 1-10, is there a way to set it to start at 8?

**Comment by Vatican-Cameos** [comment]
Use : 
`yourCarouselPicker.setCurrentItem(indexOfItemToBeSelected)` at the initialisation which would suffice your requirement.

**Comment by Brian-Yeh** [comment]
Thanks for the quick reply!
